<a href="https://colab.research.google.com/github/Sakibcheez/AutoCAD/blob/main/demo_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
 #1. Creating DataFrames and Series
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'London', 'Tokyo', 'Paris']}
df = pd.DataFrame(data)
series = pd.Series([1, 2, 3, 4, 5])
print("1. Creating DataFrame and Series:")
print("DataFrame:\n", df)
print("\nSeries:", series.values)

# 2. Basic DataFrame info
print("\n2. DataFrame info:")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:\n", df.dtypes)

# 3. Selecting data
print("\n3. Selecting data:")
print("Single column (Name):", df['Name'].tolist())
print("Multiple columns:\n", df[['Name', 'Age']])
print("First row:\n", df.iloc[0])

# 4. Filtering data
print("\n4. Filtering data:")
adults = df[df['Age'] > 28]
print("People older than 28:\n", adults)

# 5. Adding and dropping columns
df['Salary'] = [50000, 60000, 70000, 55000]
print("\n5. Adding column:")
print(df)

df_dropped = df.drop('City', axis=1)
print("\nAfter dropping 'City' column:\n", df_dropped)

1. Creating DataFrame and Series:
DataFrame:
       Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo
3    Diana   28     Paris

Series: [1 2 3 4 5]

2. DataFrame info:
Shape: (4, 3)
Columns: ['Name', 'Age', 'City']
Data types:
 Name    object
Age      int64
City    object
dtype: object

3. Selecting data:
Single column (Name): ['Alice', 'Bob', 'Charlie', 'Diana']
Multiple columns:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    Diana   28
First row:
 Name       Alice
Age           25
City    New York
Name: 0, dtype: object

4. Filtering data:
People older than 28:
       Name  Age    City
1      Bob   30  London
2  Charlie   35   Tokyo

5. Adding column:
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

After dropping 'City' column:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    Diana   28   55000

In [5]:
# 6. Statistical summary
numeric_data = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
print("\n6. Statistical summary:")
print(numeric_data.describe())

# 7. Grouping and aggregation
sales_data = pd.DataFrame({
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 180, 160],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South']
})
grouped = sales_data.groupby('Product')['Sales'].sum()
print("\n7. Grouping and aggregation:")
print("Sales by Product:\n", grouped)

# 8. Sorting data
sorted_df = df.sort_values('Age', ascending=False)
print("\n8. Sorting by Age (descending):")
print(sorted_df)

# 9. Handling missing data
df_with_na = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
    'C': [9, 10, 11, None]
})
print("\n9. Handling missing data:")
print("Original with NaN:\n", df_with_na)
print("After dropping NaN:\n", df_with_na.dropna())
print("After filling NaN with 0:\n", df_with_na.fillna(0))

# 10. Reading/writing data (simulated)
print("\n10. Data I/O operations:")
# Create sample CSV data
sample_data = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Value': [10, 20, 30, 40]
})
print("Sample data for CSV operations:\n", sample_data)
# In real usage: sample_data.to_csv('data.csv', index=False)
# In real usage: loaded_data = pd.read_csv('data.csv')

6. Statistical summary:
              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

7. Grouping and aggregation:
Sales by Product:
 Product
A    480
B    430
Name: Sales, dtype: int64

8. Sorting by Age (descending):
      Name  Age      City  Salary
2  Charlie   35     Tokyo   70000
1      Bob   30    London   60000
3    Diana   28     Paris   55000
0    Alice   25  New York   50000

9. Handling missing data:
Original with NaN:
      A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN
After dropping NaN:
      A    B    C
0  1.0  5.0  9.0
After filling NaN with 0:
      A    B     C
0  1.0  5.0   9.0
1  2.0  0.0  10.0
2  0.0  7.0  11.0
3  4.0  8.0   0.0

10. Data I/O operations:
Sample data for CSV operations:
    ID  Value
0   1     10
1   2     20
2   3     30
3   4     40

In [10]:
from google.colab import files
uploaded = files.upload()

Saving students.csv to students.csv

In [13]:
# Read the uploaded CSV file into a pandas DataFrame
df_students = pd.read_csv('students.csv')

# Display the DataFrame
print("Data from 'students.csv':")
display(df_students)

Data from 'students.csv':

       ID     Name  Age  Roll  Class Section          Phone
0   ID001  Ibrahim   18    28      9       D  8801850487291
1   ID002     Emma   14    43      9       A  8801875596567
2   ID003     Maya   12    28     10       D  8801860524295
3   ID004     Maya   11     5     11       B  8801967945667
4   ID005  Ibrahim   16    23      5       D  8801493284154
5   ID006     Maya   14    50      9       A  8801909216535
6   ID007     Zara   10    35      7       D  8801851742194
7   ID008     Noah   16    18      5       A  8801600394775
8   ID009    Ayaan   14    45     12       D  8801815752962
9   ID010     Zara   12    49      9       C  8801850463972
10  ID011    Ayaan   12    10      8       C  8801945584368
11  ID012   Sophia   12     6     11       C  8801718981886
12  ID013     Noah   18    35     10       D  8801555799518
13  ID014   Olivia   14    48      9       C  8801991223711
14  ID015     Noah   13    33      7       D  8801752819867
15  ID016     Zara   13    12     10       D  8801568868281
16  ID017  Ibrahim   14    11      9       A  8801515131076
17  ID018    Ayaan   12    18      7       C  8801951258798
18  ID019     Noah   15    44      7       B  8801487431860
19  ID020     Liam   17    24      9       C  8801730403702